config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users
  root to: 'pages#home'

  resources :cvs
  resources :jobs

end

app/models/cv.rb
class Cv < ActiveRecord::Base
  belongs_to :user

  validates :job, presence: true
  validates :first_name, presence: true
  validates :email, presence: true
  validates :city, presence: true


end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user

  validates :firm_name, presence: true
  validates :firm_email, presence: true
  validates :proposed_job, presence: true
  validates :job_city, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cvs
  has_many :jobs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
before_action :set_cv, only: [:show, :edit, :update, :destroy]

  def index
    @cvs = Cv.all
  end

  def show
  end

  def new           # GET /cvs/new
    @cv = Cv.new
  end

  def create        # POST /cvs
    @cv = Cv.new(cv_params)
    if @cv.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit          # GET /cvs/:id/edit
  end

  def update        # PATCH /cvs/:id
    @cv.update(cv_params)
    # Will raise ActiveModel::ForbiddenAttributesError

    # no need for app/views/cvs/create.html.erb
    redirect_to cvs_path
  end

  def destroy       # DELETE /cvs/:id
    @cv.destroy

    # no need for app/views/cvs/destroy.html.erb
    redirect_to cvs_path

    # <%= link_to "Delete", cv_path(cv),
    #   method: :delete,
    #   data: { confirm: "Are you sure?" } %>
  end

  private

  def cv_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:cv).permit(:job, :first_name, :last_name, :email, :city, :experience, :start_date, :comment)
  end

  def set_cv
    @cv = Cv.find(cv_params[:id])
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @job = Job.all
  end

  def show
  end

  def new           # GET /jobs/new
    @job = Job.new
  end

  def create        # POST /jobs
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit          # GET /jobs/:id/edit
  end

  def update        # PATCH /jobs/:id
    @job.update(job_params)
    # Will raise ActiveModel::ForbiddenAttributesError

    # no need for app/views/jobs/create.html.erb
    redirect_to jobs_path
  end

  def destroy       # DELETE /jobs/:id
    @job.destroy

    # no need for app/views/jobs/destroy.html.erb
    redirect_to jobs_path

    # <%= link_to "Delete", job_path(job),
    #   method: :delete,
    #   data: { confirm: "Are you sure?" } %>
  end

  private

  def job_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:job).permit(:firm_name, :firm_type, :firm_email, :proposed_job, :alternativ_job, :job_city, :job_start_date, :comment)
  end

  def set_job
    @job = Job.find(job_params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cvs = Cv.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cvs/_index.html.erb
<h1>Tous les cvs</h1>

  <div class="container">
    <div class="row">

    <% @cvs.each do |cv| %>

      <div class="col-xs-12 col-sm-4">

        <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/600/300?image=0');">
          <div class="card-category"><%= cv.job %></div>
          <div class="card-text">
            <h2><%= cv.first_name %></h2>
            <p><%= cv.city %></p>
          </div>
          <div class="card-user">
            <% if cv.job == 'barista' %>
              <%= image_tag ('barista_icon.png'), class: 'avatar avatar-bordered job_icon' %>
            <% end %>
            <% if cv.job == 'cuisinier' %>
              <%= image_tag ('cuisinier_icon.png'), class: 'avatar avatar-bordered job_icon' %>
            <% end %>
            <% if cv.job == 'patissier' %>
              <%= image_tag ('patissier_icon.png'), class: 'avatar avatar-bordered job_icon' %>
            <% end %>
          </div>
          <a href="#" class="card-link"></a>
        </div>
      </div>
    <% end %>

    </div>
  </div>

app/views/cvs/new.html.erb
<div id="page">

  <div class="columns-container">
    <div id="columns" class="">
      <div class="row profile">

        <div id="center_column" class="center_column col-xs-12 col-sm-12">

          <div class="primary_block row">

            <div class="page-container">

              <div class="page-title-container">
                <div class="page-title show-phone"><span>Déposez ici votre CV</span></div>
              </div>

              <div class="page-img-container">
                <%= image_tag ('cafe_creme.jpg'), class: 'page-img' %>
              </div>

              <div class="page-content-container">

                <div class="form-title-container hide-phone">
                  <div class="form-title"><span>Déposez ici votre CV</span></div>
                </div>
                <div class="form_ko_container" id="k_o" onsubmit="ft_show_ko(this)">
                  <div class="form_title" id="ko_inner"></div>
                </div>

                <div id="cv_form" class="cv_form">

                  <%= simple_form_for @cv, url: cvs_path, method: :post, class: 'form-control' do |f| %>
                  <%= f.input :first_name, placeholder: 'Votre Prénom', label: false, input_html: { class: 'form-control right box' } %>
                  <%= f.input :last_name, placeholder: 'Votre nom', label: false, input_html: { class: 'form-control right box' } %>
                  <%= f.input :email, as: :email, placeholder: 'Votre email', label: false, input_html: { class: 'form-control right box' } %>
                  <%= f.input :job, as: :text, placeholder: 'Job', label: false, input_html: { class: 'form-control right box' }  %>
                  <%= f.input :city, as: :text, placeholder: 'Votre Ville', label: false, input_html: { class: 'form-control right box' }  %>
                  <%= f.input :experience, as: :text, placeholder: 'Expérience', label: false, input_html: { class: 'form-control right box' }  %>
                  <%= f.input :comment, as: :text, placeholder: 'Dites nous en un peu plus...', label: false, input_html: { class: 'form-control right box' }  %>
                  <%= f.button :submit, 'Envoyer', class: "btn btn-success" %>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/jobs/_index.html.erb
<h1>Tous les jobs</h1>

<% @jobs.each do |job| %>
  <h2><%= job.firm_name %></h2>
  <p><%= job.proposed_job %></p>
<% end %>

app/views/jobs/new.html.erb
<h1>Postez votre annonce</h1>

<%= simple_form_for @job, url: jobs_path, method: :post, class: 'form-control' do |f| %>
  <%= f.input :firm_name, placeholder: 'Le nom de votre entreprise', label: false, input_html: { class: 'form-control right box' } %>
  <%= f.input :firm_type, placeholder: 'type', label: false, input_html: { class: 'form-control right box' } %>
  <%= f.input :firm_email, as: :email, placeholder: 'Votre email', label: false, input_html: { class: 'form-control right box' } %>
  <%= f.input :proposed_job, as: :text, placeholder: 'Job', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.input :job_city, as: :text, placeholder: 'Ville', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.input :job_start_date, as: :text, placeholder: 'Debut', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.input :comment, as: :text, placeholder: 'Dites nous en un peu plus...', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.button :submit, 'Envoyer', class: "btn btn-success" %>
<% end %>

app/views/jobs/wew.html.erb
<h1>Postez votre annonce</h1>

<%= simple_form_for @job, url: jobs_path, method: :post, class: 'form-control' do |f| %>
  <%= f.input :firm_name, placeholder: 'Le nom de votre entreprise', label: false, input_html: { class: 'form-control right box' } %>
  <%= f.input :firm_type, placeholder: 'type', label: false, input_html: { class: 'form-control right box' } %>
  <%= f.input :firm_email, as: :email, placeholder: 'Votre email', label: false, input_html: { class: 'form-control right box' } %>
  <%= f.input :proposed_job, as: :text, placeholder: 'Job', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.input :job_city, as: :text, placeholder: 'Ville', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.input :job_start_date, as: :text, placeholder: 'Debut', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.input :comment, as: :text, placeholder: 'Dites nous en un peu plus...', label: false, input_html: { class: 'form-control right box' }  %>
  <%= f.button :submit, 'Envoyer', class: "btn btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee People France</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Coffee People - CV pour coffeeshops">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
 -->
    <%= render 'shared/navbar' %>
    <!-- <%= render 'shared/flashes' %> -->
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="head-wrapper">

  <div class="head-img-wrapper">
    <!-- <img class="img-responsive" src="./img/magda.jpg" alt="" /> -->
    <%= image_tag 'magda.jpg', class: 'img-responsive' %>
  </div>

  <div class="head-wrapper-content page-container page-container-full text-center">
    <div class="va-container va-container-v va-container-h">
      <div class="va-middle text_header">
        <h2 class="text-branding text-white space-1">
          Recrutez la bonne personne
        </h2>
        <div class="h4 text-white space-1 hide-sm">
          Barista, cuisinier, pâtissier, des CV à portée de main.
        </div>
      </div>
    </div>
  </div>

    <div class="head-wrapper-footer hide-sm">
      <div class="text-center col-sm-12 col-md-12 col-lg-12">
        <div class="tri-search-bar">
          <button class="btn btn-left btn-grey get-cvs" type="submit">Tous les CV</button>
          <button class="btn btn-middle get-baristas" type="submit">Barista</button>
          <button class="btn btn-middle get-cuisiniers" type="submit">Cuisinier</button>
          <button class="btn btn-middle get-patissiers" type="submit">Pâtissier</button>
          <button class="btn btn-right btn-grey get-offers" type="submit">Toutes les offres</button>
        </div>
      </div>
  </div>
</div>

  <div class="head-wrapper-footer show-phone">
    <div class="tri-search-container text-center col-sm-12 col-md-12 col-lg-12">
      <div class="tri-search-bar">
        <button class="btn btn-dbl get-cvs" type="submit">Voir les CV</button>
        <button class="btn btn-dbl get-offers" type="submit">Voir les offres</button>
      </div>
    </div>
  </div>
</div>

<%= render 'cvs/index' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="">

<!--      <a href="">
      <%= image_tag "logo.png", class: "navbar-wagon-logo" %>
    </a>



    <div class="navbar-wagon-pusher"></div>x

    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profil" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Acceuil" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Déconnection" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Connection"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
 --><!--     <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  -->

















  <header id="header" class="regular-header clearfix hide-sm" role="banner">
    <div class="logo">
      <a href="">CoffeePeople</a>
    </div>


    <div class="nav pull-right help-menu list-unstyled">

      <li class="list-your-space pull-left">
        <a type="button" class="btn white-btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Publier
        </a>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
<!--           <li><a href="./cv-form.php">Un CV</a></li>
          <li><a href="./cv-form-pro.php">Une annonce</a></li>
        -->          <li>
        <%= link_to new_cv_path do %>
        <!-- <i class="fa fa-user"></i>  -->
        <%= t ".cv", default: "Un CV" %>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
        <!-- <i class="fa fa-home"></i>   -->
        <%= t ".job", default: "Une annonce" %>
        <% end %>
      </li>
    </ul>
  </li>

  <li class="pull-left">
    <% if user_signed_in? %>
    <div class="navbar-wagon-item pull-left">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
<!--               <li>
                <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profil" %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Acceuil" %>
                <% end %>
              </li>
            -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Déconnection" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>
      <%= link_to "Se connecter", "#logInModal", :class => "btn naked-btn", "data-toggle" => "modal" %>
      <% end %>
    </li>




  <!--
          <li class="pull-left">
            <a class="btn naked-btn" type="button" data-toggle="modal" data-target="#logInModal">
              Se connecter
            </a>
          </li>
           <li class="pull-left">
            <a class="btn naked-btn" type="button" data-toggle="modal" data-target="#signInModal">
              S'inscrire
            </a>
          </li>
        -->



      </div>

    </header>







  </nav>
















  <!-- Modal -->
  <div class="modal fade" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-center">
      <div class="modal-content grey-bg">
        <div class="modal-inner">

<!--       <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="myModalLabel"></h5>
      </div>
    -->

    <div class="modal-body">

      <%= render "devise/shared/new" %>
      <%= render "devise/shared/links" %>


<!--         <form action="" method="post" name="" class="validate form-inline" target="_blank" novalidate>

          <div class="email field-container required">
            <input name="email" type="email" placeholder="Adresse e-mail" spellcheck="false" class="decorative-input grey-bg form-control" required>
          </div>
          <div class="m-d-p field-container required">
            <input name="password" type="password" placeholder="Mot de passe" spellcheck="false" class="decorative-input grey-bg form-control" required>
          </div>
          <div aria-hidden="true"></div>
          <input type="submit" value="Connection" name="subscribe" id="" class="btn-submit">
        </form>
        <p>Vous n'avez pas de compte ?
          <a type="button" data-toggle="modal" data-target="#signInModal" data-dismiss="modal">
              S'inscrire
            </a>
        </p>
      -->

    </div>
  </div>
</div>
</div>
</div>



<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-center">
    <div class="modal-content grey-bg">
      <div class="modal-inner">

<!--       <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="myModalLabel"></h5>
      </div>
    -->
    <div class="modal-body">
      <form action="" method="post" name="" class="validate form-inline" target="_blank" novalidate>

        <div class="name field-container required">
          <!-- <div class="field-title required">Nom</div> -->
          <div class="">
            <label class="">
              <input type="text" class="decorative-input form-control right box" placeholder="Nom" name="first_name" onsubmit="ft_verif_filled(this)">
            </label>
          </div>
        </div>
        <div class="email field-container required">
          <!-- <label class="field-title required">Adresse e-mail</label> -->
          <input name="email" type="email" placeholder="Adresse e-mail" spellcheck="false" class="decorative-input grey-bg form-control" required>
        </div>
        <div class="m-d-p field-container required">
          <!-- <label class="field-title required">Adresse e-mail</label> -->
          <input name="password" type="password" placeholder="Mot de passe" spellcheck="false" class="decorative-input grey-bg form-control" required>
        </div>
        <div aria-hidden="true"></div>
        <input type="submit" value="Inscription" name="subscribe" id="" class="btn-submit">
      </form>
      <p>Vous êtes déjà membre ?
        <a type="button" data-toggle="modal" data-target="#logInModal" data-dismiss="modal">
          <!-- <a href="/login" class="" data-modal-href="/logInModal" data-modal-type="login"> -->

          Se connecter</a>
        </p>
      </div>
    </div>
  </div>
</div>
</div>